gui:
  showFileTree: false # for rendering changes files in a tree format
  showIcons: true
  branchColors:
    'chore': '#11aaff'
    'bug': '#fab387'
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    selectedLineBgColor:
      - "#45475a" # Surface0
    selectedRangeBgColor:
      - black
git:
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty="%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset %C(cyan)(%cn)%Creset" {{branchName}} --'
  paging:
    colorArg: always
    pager: delta --dark --paging=never
