# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/niklas/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#source "/Users/niklas/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
# ZSH_THEME="spaceship"
ZSH_THEME="agnoster"

# Plugins
plugins=(git vagrant bower composer gem laravel npm)

source $ZSH/oh-my-zsh.sh

# Aliases
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset %C(cyan)(%cn)%Creset' --abbrev-commit --date=relative"
alias gu="git up"
alias gco="git checkout"
alias gc="git commit"
alias gcm="git commit -m "
alias ga="git add"
alias gaa="git add -A"
alias gai="git add -i"
alias gap="git add -p"
alias gs="git status --short"
alias gss="git status"
alias gd="git diff"
alias gdc="git diff --cached"
alias gr="git rebase"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias gfu="git fetch upstream"
alias grud="git rebase upstream/development"
alias grum="git rebase upstream/master"
alias gfrud="gco development && gfu && grud"
alias grd="git rebase develop"
alias grm="git rebase master"
alias gfrua="gfu && gco master && grum && gco development && grud"
alias gprune="~/.dotfiles/scripts/gitprune"

alias dcu="docker-compose up -d"
alias dcd="docker-compose down"
alias dck="docker-compose kill"
alias de="docker exec -it --user $(id -u):$(id -g) "

alias art="php artisan"
alias cu="composer update"
alias cda="composer dump-autoload"
alias cr="composer require"
alias crd="composer require --dev "
alias behatrun="php artisan behat:run --format progress --env=testing"
alias vu="vagrant up"
alias vh="vagrant halt"
alias vm='vagrant ssh'
alias vr="vagrant reload"
alias vp="vagrant provision"
alias vdf="vagrant destroy -f"
alias sub='subliminal download -l en '

phpco() { docker run --init -v $PWD:/mnt/src:cached --rm -u "$(id -u):$(id -g)" frbit/phpco:latest $@; return $?; }

export PATH=vendor/bin:../../vendor/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH="$PATH:`yarn global bin`"
export PATH="$PATH:/usr/local/lib/node_modules/bin"
export PATH=~/.dotfiles/scripts:$PATH
export NODE_PATH=/usr/lib/node_modules

if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
fi

prompt_end() {
    if [[ -n $CURRENT_BG ]]; then
        print -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
    else
        print -n "%{%k%}"
    fi

    print -n "%{%f%}"
    CURRENT_BG=''

    #Adds the new line and ➜ as the start character.
    printf "\n ➜";
}

prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
  prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
    fi
}

[ -f .aws-credentials ] && source .aws-credentials
[ -f .github_token ] && source .github_token
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
