#!/bin/bash

FILE=docker/composer
if [ -f "$FILE" ]; then
    ./docker/composer "$@"
else
    docker run --user $UID:$UID -e COMPOSER_MEMORY_LIMIT=-1 --rm --interactive --tty --volume $PWD:/app composer "$@"
fi
