#!/bin/bash
echo

RED='\033[0;31m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

printf " > ${MAGENTA}Fetch origin.${NC}\n"

git fetch origin

printf " > ${MAGENTA}Pull (fast forward) master and develop..${NC}\n"

git checkout master
git pull --ff-only

git checkout develop
git pull --ff-only

printf " > ${MAGENTA}Delete merged branches.${NC}\n"

git branch --merged | grep -v -e "master" -e "develop" | xargs git branch -D

printf " > ${CYAN}Done.${NC}\n"
