[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
# family = "Geist Mono"
family = "JetBrainsMono NF"
# family = "DejaVu Sans Mono"
style = "Bold"

[font.offset]
x = 0
y = 4

[scrolling]
history = 10000

[window.padding]
x = 10
y = 10
